import NavBar from "@/components/header/nav";
import React from "react";
import AuthProvider from "./context/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";

/*
 ! TODO Finir le remplissage des metadata
 * - [ ] title
 * - referencement (SEO)
 * - Icons
 * ...
 */

export const metadata: Metadata = {
  title: "Template Basic next 13",
  authors: {
    name: "Tony Lapoche",
    url: "https://terrade-antoine.web.app/",
  },
  keywords: [
    "next",
    "typescript",
    "tailwindcss",
    "react",
    "template",
    "junior",
    "beginner",
  ],
  viewport: "width=device-width, initial-scale=1",
  description: "Generated by create next app, by tonylapoche",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={" relative"}>
        <AuthProvider>
          <header className="relative">
            <NavBar />
          </header>
          <main className="w-full absolute top-40 md:top-32 py-4 px-6">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
