import NavBar from "@/components/header/nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " relative"}>
        <header className="relative z-10">
          <NavBar />
        </header>
        <main className="absolute top-40 md:top-32 py-4 px-6">{children}</main>
      </body>
    </html>
  );
}
